# Generated by Django 3.1.6 on 2021-03-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagesplace',
            old_name='destination',
            new_name='place',
        ),
    ]
