# Generated by Django 3.1.6 on 2021-03-15 23:04

from django.db import migrations, models
import django.db.models.deletion
import mysite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20210315_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_header',
            field=models.ImageField(default='hotels/None/no-img.jpg', upload_to='hotels/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='url',
            field=models.SlugField(default='none', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ImagesHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=mysite.models.upload_gallery_hotel)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mysite.hotel')),
            ],
        ),
    ]
