# Generated by Django 3.1.6 on 2021-03-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20210315_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='minimal_price',
            field=models.TextField(default=125000),
            preserve_default=False,
        ),
    ]
