# Generated by Django 3.1.6 on 2021-03-04 16:25

from django.db import migrations, models
import django.db.models.deletion
import mysite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='image',
        ),
        migrations.CreateModel(
            name='Image_Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=mysite.models.upload_gallery_image)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mysite.destination')),
            ],
        ),
    ]
