# Generated by Django 3.1.6 on 2021-04-02 21:26

from django.db import migrations, models
import django.db.models.deletion
import mysite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20210315_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=120000, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ImagesActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=mysite.models.upload_gallery_activity)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mysite.activity')),
            ],
        ),
    ]
