# Generated by Django 3.1.6 on 2021-04-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20210402_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='website',
            field=models.TextField(default='hotelyubarta.com'),
            preserve_default=False,
        ),
    ]
